return {
    "williamboman/mason.nvim",
    opts = {
        ensure_installed = {
            "black",
            "debugpy",
            "go-debug-adapter",
            "js-debug-adapter",
            "markdownlint-cli2",
            "phpcs",
            "pyright",
            "stylua",
            "vtsls",
            "checkstyle",
            "delve",
            "gofumpt",
            "json-lsp",
            "markdown-toc",
            "php-cs-fixer",
            "python-lsp-server",
            "tailwindcss-language-server",
            "vue-language-server",
            "clangd",
            "emmet-ls",
            "goimports",
            "lua-language-server",
            "marksman",
            "php-debug-adapter",
            "ruff",
            "taplo",
            "codelldb",
            "eslint-lsp",
            "gopls",
            "markdownlint",
            "phpactor",
            "pylint",
            "shfmt",
            "typescript-language-server",
            -- 添加你在 :Mason 中看到的其他工具
        },
    },
}
